/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "brand-primary-blue": "#4d5b9e",
        "brand-primary-purple": "#6b4e90",
        "brand-dark": "#030014",
        "brand-neutral-1": "#ffffff",
        "brand-neutral-2": "#fcfcfd",
        "brand-neutral-3": "#f5f5f6",
        "brand-neutral-4": "#f0f0f1",
        "brand-neutral-5": "#d9d9dc",
        "brand-neutral-6": "#c0bfc4",
        "brand-neutral-7": "#8e8c95",
        "brand-neutral-8": "#5b5966",
        "brand-neutral-9": "#474553",
        "brand-neutral-10": "#292637",
        "brand-neutral-11": "#211f30",
        "brand-neutral-12": "#171427",
        "brand-neutral-13": "#030014",
        "brand-primary-blue-50": "#edeff5",
        "brand-primary-blue-100": "#c8cce1",
        "brand-primary-blue-200": "#adb4d2",
        "brand-primary-blue-300": "#8891be",
        "brand-primary-blue-400": "#717cb1",
        "brand-primary-blue-500": "#4d5b9e",
        "brand-primary-blue-600": "#465390",
        "brand-primary-blue-700": "#374170",
        "brand-primary-blue-800": "#2a3257",
        "brand-primary-blue-900": "#202642",
        "brand-primary-purple-50": "#f0edf4",
        "brand-primary-purple-100": "#d1c8dd",
        "brand-primary-purple-200": "#bbaecc",
        "brand-primary-purple-300": "#9c88b5",
        "brand-primary-purple-400": "#8971a6",
        "brand-primary-purple-500": "#6b4e90",
        "brand-primary-purple-600": "#614783",
        "brand-primary-purple-700": "#4c3766",
        "brand-primary-purple-800": "#3b2b4f",
        "brand-primary-purple-900": "#2d213c",
        "brand-secondary-blue-50": "#f2f5ff",
        "brand-secondary-blue-100": "#d6e0ff",
        "brand-secondary-blue-200": "#c2d1ff",
        "brand-secondary-blue-300": "#a6bcff",
        "brand-secondary-blue-400": "#95afff",
        "brand-secondary-blue-500": "#7a9bff",
        "brand-secondary-blue-600": "#6f8de8",
        "brand-secondary-blue-700": "#576eb5",
        "brand-secondary-blue-800": "#43558c",
        "brand-secondary-blue-900": "#33416b",
        "brand-secondary-purple-50": "#f9f9ff",
        "brand-secondary-purple-100": "#eeedff",
        "brand-secondary-purple-200": "#e5e4ff",
        "brand-secondary-purple-300": "#d9d7ff",
        "brand-secondary-purple-400": "#d2d0ff",
        "brand-secondary-purple-500": "#c7c4ff",
        "brand-secondary-purple-600": "#b5b2e8",
        "brand-secondary-purple-700": "#8d8bb5",
        "brand-secondary-purple-800": "#6d6c8c",
        "brand-secondary-purple-900": "#54526b",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
